export const currencyData = [
    {
      id: crypto.randomUUID(),
      pair: "USD/BRL (OTC)",
      change: "-0.64%",
      payout1: 93,
      payout2: 88,
    },
    {
      id: crypto.randomUUID(),
      pair: "NZD/CAD (OTC)",
      change: "7.5%",
      payout1: 92,
      payout2: 90,
    },
    {
      id: crypto.randomUUID(),
      pair: "USD/BDT (OTC)",
      change: "1.73%",
      payout1: 92,
      payout2: 92,
    },
    {
      id: crypto.randomUUID(),
      pair: "USD/EGP (OTC)",
      change: "-0.21%",
      payout1: 92,
      payout2: 93,
    },
    {
      id: crypto.randomUUID(),
      pair: "USD/TRY (OTC)",
      change: "-0.35%",
      payout1: 92,
      payout2: 92,
    },
    {
      id: crypto.randomUUID(),
      pair: "EUR/CHF (OTC)",
      change: "6.41%",
      payout1: 90,
      payout2: 90,
    },
    {
      id: crypto.randomUUID(),
      pair: "EUR/AUD (OTC)",
      change: "0.57%",
      payout1: 89,
      payout2: 90,
    },
    {
      id: crypto.randomUUID(),
      pair: "EUR/CAD (OTC)",
      change: "-0.37%",
      payout1: 89,
      payout2: 83,
    },
    {
      id: crypto.randomUUID(),
      pair: "USD/CAD (OTC)",
      change: "0.84%",
      payout1: 89,
      payout2: 89,
    },
    {
      id: crypto.randomUUID(),
      pair: "NZD/USD (OTC)",
      change: "1.73%",
      payout1: 88,
      payout2: 88,
    },
    {
      id: crypto.randomUUID(),
      pair: "USD/MXN (OTC)",
      change: "0.11%",
      payout1: 87,
      payout2: 87,
    },
    {
      id: crypto.randomUUID(),
      pair: "USD/PKR (OTC)",
      change: "-0.26%",
      payout1: 85,
      payout2: 88,
    },
    {
      id: crypto.randomUUID(),
      pair: "USD/ARS (OTC)",
      change: "-0.89%",
      payout1: 84,
      payout2: 84,
    },
    {
      id: crypto.randomUUID(),
      pair: "USD/EGP (OTC)",
      change: "-0.21%",
      payout1: 92,
      payout2: 93,
    },
    {
      id: crypto.randomUUID(),
      pair: "USD/TRY (OTC)",
      change: "-0.35%",
      payout1: 92,
      payout2: 92,
    },
  ];